# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['temp', 'learn', 'im_bee', 'im_wasp', 'im_mixed', 'categories', 'examples', 'intf', 'classify_image']

# %% ../app.ipynb 1
from fastai.vision.all import *
import gradio as gr

# %% ../app.ipynb 4
#this is to correct for issues when running on Windows:
#ref: https://stackoverflow.com/questions/57286486/i-cant-load-my-model-because-i-cant-put-a-posixpath

import pathlib
temp = pathlib.PosixPath
pathlib.PosixPath = pathlib.WindowsPath

# %% ../app.ipynb 5
learn = load_learner('model.pkl')

# %% ../app.ipynb 6
pathlib.PosixPath = temp

# %% ../app.ipynb 13
#show the downloaded images:
im_bee = Image.open('bee.jpg')
im_wasp = Image.open('wasp.jpg')
im_mixed = Image.open('mixed.jpg')

im_bee.thumbnail((192,192))
im_wasp.thumbnail((192,192))
im_mixed.thumbnail((192,192))

# %% ../app.ipynb 22
categories = ('bee','wasp')

def classify_image(img):
    pred, idx, probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% ../app.ipynb 25
examples = ['bee.jpg','wasp.jpg','mixed.jpg']

# %% ../app.ipynb 26
intf = gr.Interface(
    fn = classify_image,
    inputs = gr.Image(),
    outputs = gr.Textbox(),
    examples = examples
)

intf.launch(inline=False)
